# Generated by Django 2.2.6 on 2019-10-23 03:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('kind', models.CharField(blank=True, choices=[('d', 'DNG101'), ('p', 'POST'), ('t', 'TUTORIAL')], max_length=1, null=True)),
            ],
        ),
    ]
