# Generated by Django 2.2.6 on 2019-10-24 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='kind',
            new_name='category',
        ),
    ]
