# Generated by Django 3.0.2 on 2020-02-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200123_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='is_root_post',
            field=models.BooleanField(default=False),
        ),
    ]
