# Generated by Django 2.2.6 on 2019-11-04 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20191103_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug_post',
            new_name='slug',
        ),
    ]
