# Generated by Django 3.0.2 on 2020-02-02 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postcategory_is_root_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug_post',
            new_name='post_slug',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='slug_category',
            new_name='root_slug',
        ),
    ]
